spring:
  application:
    name: xiwen-server

server:
  port: 8789

security:
  basic:
    enabled: true
  user:
    name: xiwen
    password: xiwen


eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://xiwen:xiwen@localhost:8789/eureka/
